version: "3.8"
services:
    app:
        build: ./backend
        ports:
            - "3001:3001"
        environment:
            - NODE_ENV=development
            - PORT=3001
            - MONGODB_URI=mongodb://mongo:27017/taskdb
        depends_on:
            - mongo
    client:
        build: ./client
        ports:
            - "3000:5173"
        environment:
            - VITE_API_URL=http://localhost:3001/api
        depends_on:
            - app
    mongo:
        image: mongo:5.0
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
volumes:
    mongodb_data:
